#!/usr/bin/env python3
"""
bridge.py  –  WebSocket relay + C-server launcher.

Architecture:
  Browser      -> WebSocket:8080  -> bridge.py -> TCP:15001 -> game_server (C)
  game_display -> TCP:127.0.0.1:6000 -> bridge.py -> TCP:15001 -> game_server (C)

The C server generates a random 4-digit PIN on startup and includes it in
every STATE broadcast.  bridge.py reads it from stderr so it can inject
ROOM:<pin> into the WebSocket stream before the first WELCOME.
"""
import os
import signal
import socket
import subprocess
import threading
import time

from flask import Flask, send_from_directory
from flask_sock import Sock

BRIDGE_PORT  = 8080       # WebSocket / HTTP port (phones connect here)
DISPLAY_PORT = 6000       # TCP port for game_display.py
SERVER_PORT  = 15001      # internal TCP port for the C game server
STATIC_DIR   = os.path.join(os.path.dirname(__file__), 'static')
SERVER_BIN   = os.path.join(os.path.dirname(__file__), 'game_server')

app  = Flask(__name__)
sock = Sock(app)

# ── C-server management ───────────────────────────────────────────────────────

_server_proc: subprocess.Popen | None = None
_server_pin:  str | None              = None
_pin_ready    = threading.Event()


def _kill_stale() -> None:
    """Kill any game_server processes left from previous runs."""
    try:
        subprocess.run(['pkill', '-f', 'game_server'],
                       stderr=subprocess.DEVNULL, timeout=3)
        time.sleep(0.4)
    except Exception:
        pass


def _launch_server() -> None:
    global _server_proc, _server_pin
    _kill_stale()
    _server_proc = subprocess.Popen(
        [SERVER_BIN, str(SERVER_PORT)],
        stderr=subprocess.PIPE,
        stdout=subprocess.DEVNULL,
    )

    def _read_stderr():
        global _server_pin
        for raw in _server_proc.stderr:
            line = raw.decode('utf-8', errors='replace').strip()
            print('[C]', line)
            if 'PIN:' in line and not _pin_ready.is_set():
                try:
                    _server_pin = line.split('PIN:')[1].strip().split()[0]
                    _pin_ready.set()
                except Exception:
                    pass

    threading.Thread(target=_read_stderr, daemon=True).start()


def _connect_to_server(timeout: float = 5.0) -> socket.socket:
    """Open a TCP connection to the C game server; retry for up to *timeout* seconds."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            s.settimeout(1.0)
            s.connect(('127.0.0.1', SERVER_PORT))
            s.settimeout(None)
            return s
        except OSError:
            time.sleep(0.1)
    raise RuntimeError(f'Cannot connect to game_server on port {SERVER_PORT}')


# ── Relay helpers ─────────────────────────────────────────────────────────────

def _recv_lines(s: socket.socket):
    """Yield decoded, stripped lines from *s*."""
    buf = b''
    while True:
        try:
            chunk = s.recv(8192)
        except OSError:
            break
        if not chunk:
            break
        buf += chunk
        while b'\n' in buf:
            line, buf = buf.split(b'\n', 1)
            yield line.decode('utf-8', errors='replace').strip()


def _tcp_to_ws(tcp: socket.socket, ws, pin: str | None = None) -> None:
    """
    Relay TCP lines -> WebSocket.
    Injects ROOM:<pin> immediately before the first WELCOME: line so the
    phone always receives the room PIN before showing the game screen.
    """
    injected = (pin is None)   # skip injection if no pin available
    for line in _recv_lines(tcp):
        if not injected and line.startswith('WELCOME:'):
            injected = True
            try:
                ws.send(f'ROOM:{pin}')
            except Exception:
                return
        try:
            ws.send(line)
        except Exception:
            return


def _pipe(src: socket.socket, dst: socket.socket) -> None:
    """Forward raw bytes from *src* to *dst* (for display relay)."""
    try:
        while True:
            data = src.recv(8192)
            if not data:
                break
            dst.sendall(data)
    except OSError:
        pass


# ── WebSocket handler (players / phones) ─────────────────────────────────────

@sock.route('/ws')
def ws_handler(ws):
    tcp: socket.socket | None = None
    try:
        pin = _server_pin           # PIN generated by the C server
        tcp = _connect_to_server()

        # Relay C server -> WebSocket in background thread
        relay = threading.Thread(
            target=_tcp_to_ws, args=(tcp, ws, pin), daemon=True
        )
        relay.start()

        # Main thread: WebSocket -> C server
        while True:
            msg = ws.receive(timeout=35)
            if msg is None:
                break
            msg = msg.strip()
            if not msg:
                continue

            # CREATE:Name is treated as JOIN:PIN:Name (same C-server command)
            if msg.startswith('CREATE:'):
                name = msg[7:]
                msg  = f'JOIN:{pin or ""}:{name}'

            try:
                tcp.sendall((msg + '\n').encode())
            except OSError:
                break

    except Exception as e:
        print(f'[WS] error: {e}')
    finally:
        if tcp:
            try:
                tcp.close()
            except OSError:
                pass


# ── TCP relay for game_display.py ─────────────────────────────────────────────

def _handle_display(conn: socket.socket) -> None:
    """
    game_display.py connects here (DISPLAY_PORT) and sends 'DISPLAY\n'.
    We open a fresh TCP connection to the C server, register it as DISPLAY,
    then relay bytes bidirectionally.
    """
    srv: socket.socket | None = None
    try:
        srv = _connect_to_server()
        srv.sendall(b'DISPLAY\n')   # register as display with C server
        t = threading.Thread(target=_pipe, args=(srv, conn), daemon=True)
        t.start()
        _pipe(conn, srv)
    except Exception as e:
        print(f'[DISPLAY relay] {e}')
    finally:
        for s in (conn, srv):
            if s:
                try:
                    s.close()
                except OSError:
                    pass


def _display_server() -> None:
    srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    try:
        srv.bind(('127.0.0.1', DISPLAY_PORT))
    except OSError as e:
        print(f'[DISPLAY] Cannot bind on port {DISPLAY_PORT}: {e}')
        return
    srv.listen(20)
    print(f'[DISPLAY] TCP relay ready on port {DISPLAY_PORT}')
    while True:
        try:
            conn, _ = srv.accept()
            threading.Thread(target=_handle_display, args=(conn,), daemon=True).start()
        except OSError:
            break


# ── Flask HTTP routes ─────────────────────────────────────────────────────────

@app.route('/')
def index():
    return send_from_directory(STATIC_DIR, 'controller.html')


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == '__main__':
    if not os.path.isfile(SERVER_BIN):
        print(f'ERROR: {SERVER_BIN} not found.')
        print('Build:  gcc -O2 -o game_server server.c -lpthread -lm')
        raise SystemExit(1)

    # 1. Start C game server (kills stale processes first)
    _launch_server()

    # 2. Wait for PIN from C server stderr
    if _pin_ready.wait(timeout=6.0):
        print(f'[BRIDGE] Game PIN from C server: {_server_pin}')
    else:
        print('[BRIDGE] WARNING: timed out waiting for C server PIN')
        print('[BRIDGE] Check that game_server binary exists and can bind port', SERVER_PORT)

    # 3. Start display TCP relay in background
    threading.Thread(target=_display_server, daemon=True).start()
    time.sleep(0.1)

    # 4. Print banner
    try:
        probe = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        probe.connect(('8.8.8.8', 80))
        local_ip = probe.getsockname()[0]
        probe.close()
    except OSError:
        local_ip = '127.0.0.1'

    print('=' * 55)
    print('  Party Game  –  Server Ready')
    print('=' * 55)
    print(f'  Controller URL:  http://{local_ip}:{BRIDGE_PORT}/')
    print(f'  Room PIN:        {_server_pin}')
    print(f'  C game server:   port {SERVER_PORT}')
    print(f'  Display relay:   port {DISPLAY_PORT}')
    print('=' * 55)

    # 5. Run Flask (handles WebSocket + HTTP)
    app.run(host='0.0.0.0', port=BRIDGE_PORT, threaded=True)
